const ActionTypes = {
    FULL_LOADING_DATA: 'FULL_LOADING_DATA',
    LOADING_DATA: 'LOADING_DATA',
    HIDE_FULL_LOADING_DATA: 'HIDE_FULL_LOADING_DATA',
    HIDE_LOADING_DATA: 'HIDE_LOADING_DATA',
    UPDATE_AUTH: 'UPDATE_AUTH',
    UPDATE_ERROR: 'UPDATE_ERROR'
}

export default ActionTypes